# -*- coding: utf-8 -*-
"""Mapas_Acidentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSvNA18QLPVFBjcB-V8REJPPAAyy0DAn

# **Distribuição Geográfica e Temporal de Acidentes por Tipo de Animal Peçonhento no Estado de São Paulo**

## **Importando os dados**
"""

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
import json

# !pip install -q gdown
import gdown

# Registro dos acidentes com animais peçonhentos
!gdown 1N8gRhUQPYBuyrHKJK-kJFQk-hkOf33me --output dados.csv

df = pd.read_csv('dados.csv', sep=',', encoding='latin1')
df.head()

print(f"Número de registros: {len(df)}")

print("Anos das notificações")
print(df['NU_ANO'].min())
print(df['NU_ANO'].max())

# Divisões de Saúde do estado de São Paulo
!gdown 1U94NZDIqgTXQPaBtmv7ZYxJNowN7XxQW --output divisoes.gpkg

# ---- Divisões de Saúde ---- #
gdf_munic = gpd.read_file('divisoes.gpkg')

# Segunda geometria para os municipios
gdf_munic['coordenadas'] = gpd.points_from_xy(gdf_munic['Longitude'], gdf_munic['Latitude'], crs = 4326)
gdf_munic['Codigo Municipio'] = pd.to_numeric(gdf_munic['Codigo Municipio'],errors='coerce').astype('Int64')


# Agrupa por Divisão e une os municípios
limites_Macro = (gdf_munic.dissolve(by = 'Macrorregiao de Saude', as_index = False)[['Macrorregiao de Saude', 'geometry']])
limites_Regiao = (gdf_munic.dissolve(by = 'Regiao de Saude', as_index = False)[['Regiao de Saude','Macrorregiao de Saude', 'geometry']])
limites_DRS = (gdf_munic.dissolve(by = 'Departamento Regional de Saude', as_index = False)[['Departamento Regional de Saude', 'geometry']])
limites_GVE = (gdf_munic.dissolve(by = 'Grupo de Vigilancia Epidemiologica', as_index = False)[['Grupo de Vigilancia Epidemiologica', 'Departamento Regional de Saude', 'geometry']])

gdf_munic.head()

# Unidades de Atendimento
!gdown 1h4C_dfTmX-P_nGV_C-SPbXUE4O3MKbVN --output postos_atualizados.gpkg

gdf_postos = gpd.read_file('postos_atualizados.gpkg')

gdf_postos['coords'] = gdf_postos['geometry']

mun_geom = dict(zip(gdf_munic['Codigo Municipio'], gdf_munic['geometry']))
gdf_postos['geometry'] = gdf_postos['Codigo Municipio'].map(mun_geom)

# Organizando o DataFrame final
df.rename(columns =
 {
  'DT_NOTIFIC': 'Data_Not', 'SEM_NOT': 'Semana_Not',
  'NU_ANO' : 'Ano', 'ANT_DT_ACI' : 'Data_Aci',
  'ID_MUNICIP' : 'Destino', 'ANT_MUNIC_' : 'Origem',
  'ID_REGIONA': 'RegiaoSaude_Origem',
  'NU_IDADE_N':'Idade', 'CS_SEXO' : 'Sexo',
  'CS_GESTANT' : 'Gestante', 'CS_RACA' : 'Raca',
  'CS_ESCOL_N' : 'Escolaridade',
  'ANT_LOCA_1': 'Local_Picada', 'DOENCA_TRA': 'Doenca_Trabalho' ,
  'ANT_TEMPO_' : 'Tempo', 'TP_ACIDENT' : 'Acidente',
  'CON_SOROTE' : 'Soroterapia', 'EVOLUCAO' : 'Evolucao',
  'ANI_TIPO_1' : 'Outro Animal', 'ANI_SERPEN' : 'Serpente',
  'ANI_ARANHA' : 'Aranha', 'ANI_LAGART' : 'Lagarta',
  'TRA_CLASSI' : 'Gravidade',
  'NU_AMPOLAS' : 'Ampolas SAB' , 'NU_AMPOL_1' : 'Ampolas SAC',
  'NU_AMPOL_8' : 'Ampolas SAA', 'NU_AMPOL_6' : 'Ampolas SABLa',
  'NU_AMPOL_4' : 'Ampolas SAEl', 'NU_AMPO_7' : 'Ampolas SALox',
  'NU_AMPO_5' : 'Ampolas SABC', 'NU_AMPOL_9' : 'Ampolas SAEsc',
  'NU_AMPOL_3' : 'Ampolas SALon',
 }, inplace = True)

df['Origem'] = df['Origem'].astype(int)
df['Destino'] = df['Destino'].astype(int)

colunas_remover = [
    'Idade',
    'Sexo',
    'Gestante',
    'Raca',
    'Escolaridade',
    'Local_Picada',
    'Doenca_Trabalho',
    'RegiaoSaude_Origem',
    'Outro Animal', 'Serpente', 'Aranha', 'Lagarta',
    'Ampolas SAB', 'Ampolas SAC', 'Ampolas SAA', 'Ampolas SABLa',
    'Ampolas SAEl', 'Ampolas SALox', 'Ampolas SABC', 'Ampolas SAEsc',
    'Ampolas SALon', 'Data_Aci', 'Data_Not', 'Semana_Not'
]

df = df.drop(columns=colunas_remover, errors='ignore')

# Dicionários
dic_acidentes = {
    1: 'Serpente',
    2: 'Aranha',
    3: 'Escorpião',
    4: 'Lagarta',
    5: 'Abelha',
    6: 'Outros',
    9: 'Não informado'
}

dic_tempos = {
    1: 'até 1h',
    2: '1-3 h',
    3: '3-6 h',
    4: '6-12 h',
    5: '12-24 h',
    6: '24+ h',
    9: 'Ignorado'
}

dic_soroterapia = {
    1: 'Sim',
    2: 'Não',
    9: 'Ignorado'
}

dic_gravidade = {
    1: 'Leve',
    2: 'Moderado',
    3: 'Grave',
    9: 'Ignorado'
}

colunas_int = ['Acidente', 'Tempo', 'Soroterapia', 'Gravidade']

for col in colunas_int:
    df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

# Aplicação dos mapeamentos
df["Acidente"] = df["Acidente"].map(dic_acidentes)
df["Tempo"] = df["Tempo"].map(dic_tempos)
df["Soroterapia"] = df["Soroterapia"].map(dic_soroterapia)
df["Gravidade"] = df["Gravidade"].map(dic_gravidade)

df.head()

dados = df.copy()

gdf_munic.head()

# Adicionando informações
colunas = ['RRAS Orig', 'RRAS Dest', 'RS Orig', 'RS Dest', 'GVE Orig', 'GVE Dest', 'DRS Orig', 'DRS Dest', 'Coord Orig', 'Coord Dest', 'Nome Orig', 'Nome Dest']
dados[colunas] = None

Codigos_Municipios = gdf_munic['Codigo Municipio'].unique()

for m in Codigos_Municipios:
    dados.loc[dados['Origem'] == m, 'RRAS Orig'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Codigo Macrorregiao de Saude'].values[0]
    #dados.loc[dados['Origem'] == m, 'RRAS Orig'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Macrorregiao de Saude'].values[0]
    dados.loc[dados['Origem'] == m, 'RS Orig'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Codigo Regiao de Saude'].values[0]
    dados.loc[dados['Origem'] == m, 'GVE Orig'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Grupo de Vigilancia Epidemiologica'].values[0]
    dados.loc[dados['Origem'] == m, 'DRS Orig'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Departamento Regional de Saude'].values[0]
    dados.loc[dados['Origem'] == m, 'Nome Orig'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Municipio'].values[0]
    dados.loc[dados['Origem'] == m, 'Coord Orig'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['coordenadas'].values[0]


    dados.loc[dados['Destino'] == m, 'RRAS Dest'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Codigo Macrorregiao de Saude'].values[0]
    #dados.loc[dados['Destino'] == m, 'RRAS Dest'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Macrorregiao de Saude'].values[0]
    dados.loc[dados['Destino'] == m, 'RS Dest'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Codigo Regiao de Saude'].values[0]
    dados.loc[dados['Destino'] == m, 'GVE Dest'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Grupo de Vigilancia Epidemiologica'].values[0]
    dados.loc[dados['Destino'] == m, 'DRS Dest'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Departamento Regional de Saude'].values[0]
    dados.loc[dados['Destino'] == m, 'Nome Dest'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['Municipio'].values[0]
    dados.loc[dados['Destino'] == m, 'Coord Dest'] = gdf_munic[gdf_munic['Codigo Municipio'] == m]['coordenadas'].values[0]

dados.head()

"""## **Mapas**

### **Localização**
"""

def separar_casos(df_animal):
    """
    Separa os casos por município de atendimento/notificação (Destino)
    e por município de ocorrência do acidente (Origem).
    """

    df_not_mun = (
        pd.crosstab(index=df_animal['Destino'], columns='Frequência')
        .reset_index()
        .rename(columns={'Destino': 'Codigo Municipio'})
    )

    df_aci_mun = (
        pd.crosstab(index=df_animal['Origem'], columns='Frequência')
        .reset_index()
        .rename(columns={'Origem': 'Codigo Municipio'})
    )

    return df_not_mun, df_aci_mun

def contar_casos(df_not_mun, df_aci_mun, gdf_munic):
    """
    Junta as frequências de casos ao GeoDataFrame de municípios.
    """

    mun_not = gdf_munic.merge(
        df_not_mun,
        on='Codigo Municipio',
        how='left'
    )

    mun_aci = gdf_munic.merge(
        df_aci_mun,
        on='Codigo Municipio',
        how='left'
    )

    mun_not['Frequência'] = mun_not['Frequência'].fillna(0).astype(int)
    mun_aci['Frequência'] = mun_aci['Frequência'].fillna(0).astype(int)

    mun_not['NUM_CASOS_LOG'] = np.log1p(mun_not['Frequência'])
    mun_aci['NUM_CASOS_LOG'] = np.log1p(mun_aci['Frequência'])

    return mun_not, mun_aci

def mapa_not(gdf_plot, animal, aci=False):
    """
    Gera mapa interativo de notificações ou acidentes por município.
    Usa os polígonos da coluna geometry.
    """

    tipo = 'Acidentes' if aci else 'Notificações de Acidentes'

    gdf_plot = gdf_plot.copy()

    # Garantir que a geometria ativa é a coluna de polígonos
    gdf_plot = gpd.GeoDataFrame(
        gdf_plot,
        geometry='geometry',
        crs=gdf_plot.crs
    )

    # Garantir CRS compatível com Plotly/Mapbox
    if gdf_plot.crs is not None and gdf_plot.crs.to_epsg() != 4326:
        gdf_plot = gdf_plot.to_crs(epsg=4326)

    # Chave para cruzamento com o GeoJSON
    gdf_plot['cod_mun_str'] = gdf_plot['Codigo Municipio'].astype(str)

    # GeoJSON só com colunas seguras
    gdf_geo = gdf_plot[
        ['cod_mun_str', 'Municipio', 'geometry']
    ].copy()

    geojson = gdf_geo.__geo_interface__

    # DataFrame para o Plotly SEM colunas geométricas
    df_plot = gdf_plot[
        ['cod_mun_str', 'Municipio', 'Frequência', 'NUM_CASOS_LOG']
    ].copy()

    fig = px.choropleth_mapbox(
        df_plot,
        geojson=geojson,
        locations='cod_mun_str',
        featureidkey='properties.cod_mun_str',
        color='NUM_CASOS_LOG',
        color_continuous_scale='YlOrRd',
        hover_name='Municipio',
        hover_data={
            'Frequência': True,
            'NUM_CASOS_LOG': False,
            'cod_mun_str': False
        },
        mapbox_style='carto-positron',
        zoom=6.0,
        # center={'lat': -22.6, 'lon': -48.3},
        # zoom=5.6,
        center={'lat': -22.6, 'lon': -48.4},
        opacity=0.85,
        labels={
            'Frequência': 'Número de casos',
            'NUM_CASOS_LOG': 'Casos em escala logarítmica'
        }
    )

    fig.update_layout(
        width=1300,
        height=620,

        title=dict(
            text=f'<b>Mapa de {tipo} com {animal} por Município</b>',
            x=0.5,
            xanchor='center',
            font=dict(size=20, family='Arial', color='black')
        ),

        font=dict(
            family='Arial',
            size=14,
            color='black'
        ),

        coloraxis_colorbar=dict(
            title=dict(
                text='<b>Casos<br>(escala log)</b>',
                font=dict(size=15, family='Arial', color='black')
            ),
            tickfont=dict(size=13, family='Arial', color='black'),
            thickness=18,
            len=0.78,
            x=1.02,
            y=0.50,
            outlinewidth=0
        ),

        hoverlabel=dict(
            bgcolor='white',
            font_size=13,
            font_family='Arial'
        ),

        margin=dict(r=70, t=70, l=0, b=0)
    )

    fig.show()

def mapa_not_est(gdf_plot, animal, aci=False):
    """
    Gera mapa estático de notificações ou acidentes por município.
    Usa os polígonos da coluna geometry.
    """

    tipo = 'Acidentes' if aci else 'Notificações de Acidentes'

    gdf_plot = gdf_plot.copy()

    # Garante que a geometria ativa é a coluna de polígonos
    gdf_plot = gpd.GeoDataFrame(
        gdf_plot,
        geometry='geometry',
        crs=gdf_plot.crs
    )

    # Garante que não há valores ausentes nas colunas usadas
    gdf_plot['Frequência'] = gdf_plot['Frequência'].fillna(0).astype(int)
    gdf_plot['NUM_CASOS_LOG'] = np.log1p(gdf_plot['Frequência'])

    fig, ax = plt.subplots(1, 1, figsize=(15, 15))

    gdf_plot.plot(
        column='NUM_CASOS_LOG',
        cmap='YlOrRd',
        legend=True,
        legend_kwds={
            'label': 'Número de casos (escala logarítmica)',
            'orientation': 'horizontal'
        },
        edgecolor='white',
        linewidth=0.3,
        ax=ax
    )

    ax.set_title(
        f'Mapa de {tipo} com {animal} por município - São Paulo',
        fontsize=18
    )

    ax.axis('off')
    plt.show()

import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

def mapa_not_est_com_pesa(gdf_plot, animal, aci=False):
    """
    Gera mapa estático de notificações ou acidentes por município,
    com PESA em triângulos azuis e contorno das RRAS em preto.
    """

    tipo = 'Acidentes' if aci else 'Notificações de Acidentes'

    # =========================
    # 1. Preparar GeoDataFrame
    # =========================

    gdf_plot = gdf_plot.copy()

    gdf_plot = gpd.GeoDataFrame(
        gdf_plot,
        geometry='geometry',
        crs=gdf_plot.crs
    )

    gdf_plot['Frequência'] = gdf_plot['Frequência'].fillna(0).astype(int)
    gdf_plot['NUM_CASOS_LOG'] = np.log1p(gdf_plot['Frequência'])

    # =========================
    # 2. Cores e estilos
    # =========================

    cor_rras = 'black'
    cor_pesa = '#1565C0'  # azul forte
    cor_borda_municipio = 'white'

    plt.rcParams['font.family'] = 'DejaVu Sans'

    # =========================
    # 3. Criar figura
    # =========================

    fig, ax = plt.subplots(figsize=(16, 14))

    # =========================
    # 4. Plotar municípios por número de casos
    # =========================

    gdf_plot.plot(
        column='NUM_CASOS_LOG',
        cmap='YlOrRd',
        legend=True,
        legend_kwds={
            'label': 'Número de casos (escala logarítmica)',
            'orientation': 'vertical',
            'shrink': 0.50,
            'pad': 0.02
        },
        edgecolor=cor_borda_municipio,
        linewidth=0.3,
        ax=ax,
        zorder=1
    )

    # Ajustar fonte da barra de cores
    cbar = fig.axes[-1]
    cbar.set_ylabel(
        'Número de casos (escala logarítmica)',
        fontsize=12,
        fontweight='bold'
    )
    cbar.tick_params(labelsize=12)

    # =========================
    # 5. Plotar postos com soro como triângulos azuis
    # =========================

    postos_com_soro = gdf_postos[gdf_postos['Tem Soro'] == 1].copy()

    postos_com_soro.set_geometry('coords').plot(
        ax=ax,
        marker='^',
        color=cor_pesa,
        markersize=30,
        edgecolor='black',
        linewidth=0.7,
        zorder=5
    )

    # =========================
    # 6. Contorno das RRAS em preto
    # =========================

    limites_Macro.boundary.plot(
        ax=ax,
        color=cor_rras,
        linewidth=2.0,
        zorder=4
    )

    # =========================
    # 7. Legenda manual
    # =========================

    legenda = [
        Line2D(
            [0], [0],
            marker='^',
            color='w',
            label='PESA',
            markerfacecolor=cor_pesa,
            markeredgecolor='black',
            markersize=12
        ),
        Line2D(
            [0], [0],
            linestyle='-',
            color=cor_rras,
            label='RRAS',
            linewidth=2.0
        )
    ]

    leg = ax.legend(
        handles=legenda,
        loc='lower left',
        bbox_to_anchor=(0.03, 0.05),
        prop={'size': 17},
        frameon=True,
        facecolor='white',
        edgecolor='black',
        framealpha=0.95
    )

    # =========================
    # 8. Título e ajustes finais
    # =========================

    ax.set_title(
        f'Mapa de {tipo} com {animal} por município',
        fontsize=20,
        fontweight='bold',
        color='black',
        pad=20
    )

    ax.axis('off')

    plt.tight_layout()
    plt.show()

"""### **Visualizações - Animais Peçonhentos**"""

animal = 'Animais Peçonhentos'

df_animal = dados.copy()

df_not_mun_geral, df_aci_mun_geral = separar_casos(dados)

mun_not_geral, mun_aci_geral = contar_casos(
    df_not_mun_geral,
    df_aci_mun_geral,
    gdf_munic
)

mapa_not(mun_not_geral, animal, False)

top20_mun_not = (
    mun_not_geral
    .sort_values('Frequência', ascending=False)
    .head(20)
)

top20_mun_not[['Municipio', 'Frequência']]

mapa_not(mun_aci_geral, animal, True)

mapa_not_est_com_pesa(mun_aci_geral, animal, aci=True)

"""#####**CINZA**"""

# mapa_not(mun_aci_geral, animal, True)
tipo = 'Acidentes'
animal = 'Animais Peçonhentos'

gdf_plot = mun_aci_geral.copy()

# Garantir que a geometria ativa é a coluna de polígonos
gdf_plot = gpd.GeoDataFrame(
    gdf_plot,
    geometry='geometry',
    crs=gdf_plot.crs
)

# Garantir CRS compatível com Plotly/Mapbox
if gdf_plot.crs is not None and gdf_plot.crs.to_epsg() != 4326:
    gdf_plot = gdf_plot.to_crs(epsg=4326)

# Chave para cruzamento com o GeoJSON
gdf_plot['cod_mun_str'] = gdf_plot['Codigo Municipio'].astype(str)

# GeoJSON só com colunas seguras
gdf_geo = gdf_plot[
    ['cod_mun_str', 'Municipio', 'geometry']
].copy()

geojson = gdf_geo.__geo_interface__

# DataFrame para o Plotly SEM colunas geométricas
df_plot = gdf_plot[
    ['cod_mun_str', 'Municipio', 'Frequência', 'NUM_CASOS_LOG']
].copy()

fig = px.choropleth_mapbox(
    df_plot,
    geojson=geojson,
    locations='cod_mun_str',
    featureidkey='properties.cod_mun_str',
    color='NUM_CASOS_LOG',
    color_continuous_scale='Greys',
    hover_name='Municipio',
    hover_data={
        'Frequência': True,
        'NUM_CASOS_LOG': False,
        'cod_mun_str': False
    },
    mapbox_style='carto-positron',
    zoom=5.6,
    center={'lat': -22.9, 'lon': -48.4},
    opacity=0.8,
    labels={
        'Frequência': 'Nº de casos',
        'NUM_CASOS_LOG': 'Nº de casos (escala log)'
    },
    title=f'Mapa de {tipo} com {animal} por município - São Paulo'
)

fig.update_layout(
    margin={'r': 0, 't': 50, 'l': 0, 'b': 0}
)

fig.show()

top20_mun_aci = (
    mun_aci_geral
    .sort_values('Frequência', ascending=False)
    .head(20)
)

top20_mun_aci[['Municipio', 'Frequência']]

mun_menor_freq = mun_aci_geral[mun_aci_geral['Frequência'] == mun_aci_geral['Frequência'].min()]

mun_menor_freq[['Municipio', 'Frequência']]

mapa_not_est(mun_not_geral, animal, aci=False)

mapa_not_est(mun_aci_geral, animal, aci=True)

"""#### **Considerando a População**"""

def separar_casos_anual(df_animal, menor_ano, maior_ano):
    """
    Separa os casos por município de atendimento/notificação (Destino)
    e por município de ocorrência do acidente (Origem)
    para cada ano.
    """

    # Filtra os dados
    df_animal = df_animal[
        (df_animal['Ano'] >= menor_ano) &
        (df_animal['Ano'] <= maior_ano)
    ]

    # Destino por Ano
    df_not_mun = df_animal.groupby(['Destino','Ano']).size().reset_index(name='Frequência')
    df_not_mun = df_not_mun.rename(columns={'Destino': 'Codigo Municipio'})

    # Origem por Ano
    df_aci_mun = df_animal.groupby(['Origem','Ano']).size().reset_index(name='Frequência')
    df_aci_mun = df_aci_mun.rename(columns={'Origem': 'Codigo Municipio'})

    return df_not_mun, df_aci_mun

df_not_mun_anual, df_aci_mun_anual = separar_casos_anual(dados, 2007, 2025)

def contar_casos_populacao(df_not_mun, df_aci_mun, gdf_munic, habitantes = 100000):
    """
    Junta a taxa de incidência padronizada de casos ao GeoDataFrame de municípios.
    Por padrão, para 100.000 habitantes.
    """

    if 'Ano' in df_not_mun.columns:
      # Remove a coluna 'Ano'
      df_not_mun = df_not_mun.drop(columns=['Ano'])
      df_aci_mun = df_aci_mun.drop(columns=['Ano'])


      # # Substitui os registros com mesmo 'Codigo Municipio' por um único
      # # contendo a média de casos
      df_not_mun = df_not_mun.groupby('Codigo Municipio').mean().reset_index()
      df_aci_mun = df_aci_mun.groupby('Codigo Municipio').mean().reset_index()

    # Agrupa com o GeoDF
    mun_not = gdf_munic.merge(
        df_not_mun,
        on='Codigo Municipio',
        how='left'
    )

    mun_aci = gdf_munic.merge(
        df_aci_mun,
        on='Codigo Municipio',
        how='left'
    )

    # Taxa (média) de incidência
    col_populacao = 'Populacao Estimada IBGE 2022'

    mun_not['Frequência'] = mun_not['Frequência'].fillna(0).astype(int)
    mun_aci['Frequência'] = mun_aci['Frequência'].fillna(0).astype(int)

    mun_not['Incidência'] = mun_not['Frequência'] / mun_not[col_populacao]
    mun_aci['Incidência'] = mun_aci['Frequência'] / mun_aci[col_populacao]

    mun_not['Taxa Padronizada'] = mun_not['Incidência'] * habitantes
    mun_aci['Taxa Padronizada'] = mun_aci['Incidência'] * habitantes

    # mun_not['Taxa Padronizada'] = mun_not['Frequência'] * habitantes
    # mun_aci['Taxa Padronizada'] = mun_aci['Frequência'] * habitantes

    mun_not['TAXA_LOG'] = np.log1p(mun_not['Taxa Padronizada'])
    mun_aci['TAXA_LOG'] = np.log1p(mun_aci['Taxa Padronizada'])

    return mun_not, mun_aci

mun_not_freq_geral, mun_aci_freq_geral = contar_casos_populacao(df_not_mun_geral, df_aci_mun_geral, gdf_munic)

mun_not_freq, mun_aci_freq = contar_casos_populacao(df_not_mun_anual, df_aci_mun_anual, gdf_munic)

def mapa_aci_est_com_pesa_pop(gdf_plot, animal, coluna_plot, legenda_barra, aci=False):
    """
    Gera mapa estático de notificações ou acidentes por município,
    com PESA em triângulos azuis e contorno das RRAS em preto.
    """

    tipo = 'Acidentes' if aci else 'Notificações de Acidentes'

    # =========================
    # 1. Preparar GeoDataFrame
    # =========================

    gdf_plot = gdf_plot.copy()

    gdf_plot = gpd.GeoDataFrame(
        gdf_plot,
        geometry='geometry',
        crs=gdf_plot.crs
    )

    # =========================
    # 2. Cores e estilos
    # =========================

    cor_rras = 'black'
    cor_pesa = '#1565C0'  # azul forte
    cor_borda_municipio = 'white'

    plt.rcParams['font.family'] = 'DejaVu Sans'

    # =========================
    # 3. Criar figura
    # =========================

    fig, ax = plt.subplots(figsize=(16, 14))

    # =========================
    # 4. Plotar municípios por número de casos
    # =========================

    gdf_plot.plot(
        column=coluna_plot,
        cmap='YlOrRd',
        legend=True,
        legend_kwds={
            # 'label': 'Número de casos (escala logarítmica)',
            # 'label': 'Taxa de Incidência por 100.000 habitantes (escala logarítmica)',  # não aparece no plot
            # 'orientation': 'vertical',
            'orientation': 'horizontal',
            'shrink': 0.50,
            'pad': 0.02
        },
        edgecolor=cor_borda_municipio,
        linewidth=0.3,
        ax=ax,
        zorder=1
    )

    cbar = fig.axes[-1]

    cbar.set_xlabel(
        legenda_barra,
        fontsize=12,
        fontweight='bold',
        labelpad=12
    )

    cbar.xaxis.set_label_position('bottom')  # texto embaixo da escala
    cbar.xaxis.set_ticks_position('bottom')
    cbar.tick_params(axis='x', labelsize=12)

    # =========================
    # 5. Plotar postos com soro como triângulos azuis
    # =========================

    postos_com_soro = gdf_postos[gdf_postos['Tem Soro'] == 1].copy()

    postos_com_soro.set_geometry('coords').plot(
        ax=ax,
        marker='^',
        color=cor_pesa,
        markersize=30,
        edgecolor='black',
        linewidth=0.7,
        zorder=5
    )

    # =========================
    # 6. Contorno das RRAS em preto
    # =========================

    limites_Macro.boundary.plot(
        ax=ax,
        color=cor_rras,
        linewidth=2.0,
        zorder=4
    )

    # =========================
    # 7. Legenda manual
    # =========================

    legenda = [
        Line2D(
            [0], [0],
            marker='^',
            color='w',
            label='PESA',
            markerfacecolor=cor_pesa,
            markeredgecolor='black',
            markersize=12
        ),
        Line2D(
            [0], [0],
            linestyle='-',
            color=cor_rras,
            label='RRAS',
            linewidth=2.0
        )
    ]

    leg = ax.legend(
        handles=legenda,
        loc='lower left',
        bbox_to_anchor=(0.03, 0.05),
        prop={'size': 17},
        frameon=True,
        facecolor='white',
        edgecolor='black',
        framealpha=0.95
    )

    # =========================
    # 8. Título e ajustes finais
    # =========================

    ax.set_title(
        f'Mapa de {tipo} com {animal} por município',
        fontsize=20,
        fontweight='bold',
        color='black',
        pad=20
    )

    ax.axis('off')

    plt.tight_layout()
    plt.show()

# legenda_mapa = 'Taxa de Incidência por 100.000 habitantes (escala logarítmica)'
legenda_mapa = 'Taxa de Incidência por 100.000 habitantes'
mapa_aci_est_com_pesa_pop(mun_aci_freq_geral, 'Animais Peçonhentos', 'Taxa Padronizada', legenda_mapa, aci=True)

# legenda_mapa = 'Taxa de Incidência por 100.000 habitantes'
legenda_mapa = 'Taxa de Incidência por 100.000 habitantes'
mapa_aci_est_com_pesa_pop(mun_aci_freq, 'Animais Peçonhentos', 'Taxa Padronizada', legenda_mapa, aci=True)

top_20_aci_freq = (
    mun_aci_freq
    .sort_values('Taxa Padronizada', ascending=False)
    .head(20)
)

top_20_aci_freq[['Municipio', 'Taxa Padronizada']]

mapa_aci_est_com_pesa_pop(mun_not_freq, 'Animais Peçonhentos', 'TAXA_LOG', legenda_mapa, aci=False)

top_20_not_freq = (
    mun_not_freq
    .sort_values('Frequência', ascending=False)
    .head(20)
)

top_20_not_freq[['Municipio', 'Frequência']]

"""#### **Razão de Incidência Padronizada (SMR)**"""

def_not_mun_anual, df_aci_mun_anual = separar_casos(dados)

def smr(df_mun, df_anim, gdf_munic):

  # Agrupa com o GeoDF
  df_final = gdf_munic.merge(
      df_mun,
      on='Codigo Municipio',
      how='left'
  )

  # Total
  pop_total = gdf_munic['Populacao Estimada IBGE 2022'].sum()
  casos_total = df_mun['Frequência'].sum()
  anos = len(df_mun['Ano'].unique())

  taxa_referencia = (casos_total / pop_total) / anos

  # Espectativa
  df_final['Casos Esperados Anual'] = df_final['Populacao Estimada IBGE 2022'] * taxa_referencia
  df_final['Casos Esperados Período'] = df_final['Casos Esperados Anual'] * anos

  # SMR = Casos Observados / Casos Esperados
  df_final['SMR'] = df_final['Frequência'] / df_final['Casos Esperados Período']

  #
  df_final['Taxa Padronizada'] = df_final['SMR'] * (taxa_referencia * 100000)

  return df_final

df_smr = smr(df_not_mun_anual, dados, gdf_munic)

legenda_mapa = 'Taxa Padronizada por 100.000 habitantes'
mapa_aci_est_com_pesa_pop(df_smr, 'Animais Peçonhentos', 'Taxa Padronizada', legenda_mapa, aci=False)

"""### **Tempo de Atendimento**

#### Auxiliares
"""

ordem_tempo = [
    'até 1h',
    '1-3 h',
    '3-6 h',
    '6-12 h',
    '12-24 h',
    '24+ h'
]

def percentil_75_categorico(row, tempo_cols):
    """
    Calcula a categoria de tempo correspondente ao percentil 75%,
    com base na frequência acumulada das categorias de tempo.
    """

    total = sum(row[col] for col in tempo_cols)

    if total == 0:
        return np.nan

    limite = total * 0.75
    acumulado = 0

    for col in tempo_cols:
        acumulado += row[col]

        if acumulado >= limite:
            return col

    return np.nan

def contar_tempo(df_animal, gdf_munic, animal, coluna_municipio='Destino'):
    """
    Gera um mapa coroplético com a categoria de tempo até 75% dos atendimentos,
    calculado por município.

    coluna_municipio:
        'Destino' -> município de atendimento/notificação
        'Origem'  -> município de ocorrência do acidente
    """

    # Crosstab dos tempos por município
    df_tempo = pd.crosstab(
        index=df_animal[coluna_municipio],
        columns=df_animal['Tempo']
    ).reset_index()

    df_tempo = df_tempo.rename(columns={coluna_municipio: 'Codigo Municipio'})

    # Padronizar tipo da chave
    df_tempo['Codigo Municipio'] = pd.to_numeric(
        df_tempo['Codigo Municipio'],
        errors='coerce'
    ).astype('Int64')

    # Remove "Ignorado" do cálculo do percentil
    if 'Ignorado' in df_tempo.columns:
        df_tempo = df_tempo.drop(columns=['Ignorado'])

    # Garantir que todas as colunas de tempo existam
    for col in ordem_tempo:
        if col not in df_tempo.columns:
            df_tempo[col] = 0

    # Calcular percentil 75 categórico
    df_tempo['percentil_75'] = df_tempo.apply(
        lambda row: percentil_75_categorico(row, ordem_tempo),
        axis=1
    )

    # Copiar o GeoDataFrame e garantir a geometria correta
    gdf_plot = gdf_munic.copy()
    gdf_plot = gpd.GeoDataFrame(
        gdf_plot,
        geometry='geometry',
        crs=gdf_plot.crs
    )

    # Padronizar tipo da chave
    gdf_plot['Codigo Municipio'] = pd.to_numeric(
        gdf_plot['Codigo Municipio'],
        errors='coerce'
    ).astype('Int64')

    # Merge
    gdf_plot = gdf_plot.merge(
        df_tempo[['Codigo Municipio', 'percentil_75']],
        on='Codigo Municipio',
        how='left'
    )

    # Ordenação categórica
    gdf_plot['percentil_75'] = pd.Categorical(
        gdf_plot['percentil_75'],
        categories=ordem_tempo,
        ordered=True
    )

    # Converter CRS se necessário
    if gdf_plot.crs is not None and gdf_plot.crs.to_epsg() != 4326:
        gdf_plot = gdf_plot.to_crs(epsg=4326)

    # Criar chave string para o plot
    gdf_plot['cod_mun_str'] = gdf_plot['Codigo Municipio'].astype(str)

    # GeoJSON apenas com colunas seguras
    gdf_geo = gdf_plot[['cod_mun_str', 'Municipio', 'geometry']].copy()
    geojson = gdf_geo.__geo_interface__

    # DataFrame sem colunas geométricas
    df_plot = gdf_plot[['cod_mun_str', 'Municipio', 'percentil_75']].copy()

    fig = px.choropleth_mapbox(
        df_plot,
        geojson=geojson,
        locations='cod_mun_str',
        color='percentil_75',
        featureidkey='properties.cod_mun_str',
        hover_name='Municipio',
        hover_data={
            'cod_mun_str': False
        },
        mapbox_style='carto-positron',
        zoom=5.6,
        center={'lat': -22.9, 'lon': -48.4},
        opacity=0.8,
        color_discrete_sequence=px.colors.qualitative.Safe,
        category_orders={'percentil_75': ordem_tempo},
        labels={'percentil_75': 'Tempo até 75% dos atendimentos'},
        title=f'Mapa do tempo de atendimento (percentil 75%) dos acidentes com {animal}'
    )

    fig.update_layout(
        margin={'r': 0, 't': 50, 'l': 0, 'b': 0}
    )

    fig.show()
    return df_tempo

"""#### Visualizações"""

tempo_geral = contar_tempo(df_animal=df_animal, gdf_munic=gdf_munic, animal=animal, coluna_municipio='Destino')

tempo_geral

tempo_geral['percentil_75'].value_counts()

tempo24 = tempo_geral[tempo_geral['percentil_75'] == '24+ h']
tempo24

t = tempo24['Codigo Municipio'].tolist()

for m in t:
    print(gdf_munic[gdf_munic['Codigo Municipio'] == m]['Municipio'].values[0])

tempo12 = tempo_geral[tempo_geral['percentil_75'] == '12-24 h']
tempo12

p = tempo12['Codigo Municipio'].tolist()

for m in p:
    print(gdf_munic[gdf_munic['Codigo Municipio'] == m]['Municipio'].values[0])

"""### Visualizações por tipo de animal

#### **Serpente**
"""

# animal = 'Serpente'

# df_animal = dados[dados['Acidente'] == animal].copy()

# df_not_mun, df_aci_mun = separar_casos(df_animal)

# mun_not, mun_aci = contar_casos(
#     df_not_mun,
#     df_aci_mun,
#     gdf_munic
# )

# mapa_not(mun_not, animal, False)

# mapa_not(mun_aci, animal, True)

# mapa_not_est(mun_not, animal, aci=False)

# mapa_not_est(mun_aci, animal, aci=True)

# contar_tempo(df_animal=df_animal, gdf_munic=gdf_munic, animal=animal, coluna_municipio='Destino')

"""#### **Aranha**"""

# animal = 'Aranha'

# df_animal = dados[dados['Acidente'] == animal].copy()

# df_not_mun, df_aci_mun = separar_casos(df_animal)

# mun_not, mun_aci = contar_casos(
#     df_not_mun,
#     df_aci_mun,
#     gdf_munic
# )

# mapa_not(mun_not, animal, False)

# mapa_not(mun_aci, animal, True)

# mapa_not_est(mun_not, animal, aci=False)

# mapa_not_est(mun_aci, animal, aci=True)

# contar_tempo(df_animal=df_animal, gdf_munic=gdf_munic, animal=animal, coluna_municipio='Destino')

"""#### **Escorpião**"""

# animal = 'Escorpião'

# df_animal = dados[dados['Acidente'] == animal].copy()

# df_not_mun, df_aci_mun = separar_casos(df_animal)

# mun_not, mun_aci = contar_casos(
#     df_not_mun,
#     df_aci_mun,
#     gdf_munic
# )

# mapa_not(mun_not, animal, False)

# mapa_not(mun_aci, animal, True)

# mapa_not_est(mun_not, animal, aci=False)

# mapa_not_est(mun_aci, animal, aci=True)

# contar_tempo(df_animal=df_animal, gdf_munic=gdf_munic, animal=animal, coluna_municipio='Destino')

"""#### **Lagarta**"""

# animal = 'Lagarta'

# df_animal = dados[dados['Acidente'] == animal].copy()

# df_not_mun, df_aci_mun = separar_casos(df_animal)

# mun_not, mun_aci = contar_casos(
#     df_not_mun,
#     df_aci_mun,
#     gdf_munic
# )

# mapa_not(mun_not, animal, False)

# mapa_not(mun_aci, animal, True)

# mapa_not_est(mun_not, animal, aci=False)

# mapa_not_est(mun_aci, animal, aci=True)

# contar_tempo(df_animal=df_animal, gdf_munic=gdf_munic, animal=animal, coluna_municipio='Destino')

"""#### **Abelha**"""

# animal = 'Abelha'

# df_animal = dados[dados['Acidente'] == animal].copy()

# df_not_mun, df_aci_mun = separar_casos(df_animal)

# mun_not, mun_aci = contar_casos(
#     df_not_mun,
#     df_aci_mun,
#     gdf_munic
# )

# mapa_not(mun_not, animal, False)

# mapa_not(mun_aci, animal, True)

# mapa_not_est(mun_not, animal, aci=False)

# mapa_not_est(mun_aci, animal, aci=True)

# contar_tempo(df_animal=df_animal, gdf_munic=gdf_munic, animal=animal, coluna_municipio='Destino')

"""## **Fluxo de pacientes**

### Análise geral
"""

sem_fluxo = dados[dados['Coord Dest'] == dados['Coord Orig']]
sem_fluxo

com_fluxo = dados[dados['Coord Dest'] != dados['Coord Orig']]
com_fluxo

diferente_rras = com_fluxo[com_fluxo['RRAS Orig'] != com_fluxo['RRAS Dest']]
diferente_rras

print('Tamanho dos conjuntos entre 2007 e 2025:')
print(f'Sem fluxo: {len(sem_fluxo)}, {(len(sem_fluxo) *100) /len(dados)}%')
print(f'Com fluxo intermunicipal: {len(com_fluxo)}, {(len(com_fluxo) *100) /len(dados)}%')
print(f'Com fluxo e RRAS diferentes: {len(diferente_rras)}, {(len(diferente_rras) *100) /len(dados)}% e {(len(diferente_rras) *100) /len(com_fluxo)}%')

dados_recentes = dados[dados['Ano'] >= 2023]
#dados_recentes = dados[dados['Ano'] >= 2020]

sem_fluxo_recentes = dados_recentes[dados_recentes['Coord Dest'] == dados_recentes['Coord Orig']]
com_fluxo_recentes = dados_recentes[dados_recentes['Coord Dest'] != dados_recentes['Coord Orig']]
diferente_rras_recentes = com_fluxo_recentes[com_fluxo_recentes['RRAS Orig'] != com_fluxo_recentes['RRAS Dest']]

#print('Tamanho dos conjuntos entre 2023 e 2025:')
print('Tamanho dos conjuntos entre 2020 e 2025:')
print(f'Sem fluxo: {len(sem_fluxo_recentes)}, {(len(sem_fluxo_recentes) *100) /len(dados_recentes)}%')
print(f'Com fluxo intermunicipal: {len(com_fluxo_recentes)}, {(len(com_fluxo_recentes) *100) /len(dados_recentes)}%')
print(f'Com fluxo e RRAS diferentes: {len(diferente_rras_recentes)}, {(len(diferente_rras_recentes) *100) /len(dados_recentes)}% e {(len(diferente_rras_recentes) *100) /len(com_fluxo_recentes)}%')

"""### Agrupamento dos fluxos

#### Municípios
"""

com_fluxo['Nome Dest'].value_counts()

com_fluxo_recentes['Nome Dest'].value_counts()

com_fluxo['Nome Orig'].value_counts()

com_fluxo_recentes['Nome Orig'].value_counts()

"""#### RRAS"""

com_fluxo['RRAS Orig'].value_counts()

com_fluxo['RRAS Dest'].value_counts()

com_fluxo_recentes['RRAS Orig'].value_counts()

com_fluxo_recentes['RRAS Dest'].value_counts()

diferente_rras['RRAS Orig'].value_counts()

diferente_rras['RRAS Dest'].value_counts()

diferente_rras_recentes['RRAS Orig'].value_counts()

diferente_rras_recentes['RRAS Dest'].value_counts()

"""##### Ajustes de distância e contagem das ocorrências

"""

import numpy as np

def distancia_haversine_km(p1, p2):
    """
    Calcula distância em linha reta entre dois pontos geográficos em km.
    Espera pontos shapely Point, com:
    x = longitude
    y = latitude
    """

    if p1 is None or p2 is None:
        return np.nan

    if pd.isna(p1) or pd.isna(p2):
        return np.nan

    lat1, lon1 = p1.y, p1.x
    lat2, lon2 = p2.y, p2.x

    R = 6371  # raio médio da Terra em km

    lat1_rad = np.radians(lat1)
    lat2_rad = np.radians(lat2)
    dlat = np.radians(lat2 - lat1)
    dlon = np.radians(lon2 - lon1)

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

colunas_groupby = [
    'Destino',
    'Origem',
    'RRAS Orig',
    'RRAS Dest',
    'RS Orig',
    'RS Dest',
    'GVE Orig',
    'GVE Dest',
    'DRS Orig',
    'DRS Dest',
    'Nome Orig',
    'Nome Dest'
]

fluxos_por_animal = {}

for animal in com_fluxo_recentes['Acidente'].dropna().unique():

    df_animal = com_fluxo_recentes[
        com_fluxo_recentes['Acidente'] == animal
    ].copy()

    fluxo_animal = (
        df_animal
        .groupby(colunas_groupby, dropna=False, sort=False)
        .agg(
            Total=('Acidente', 'size'),
            Coord_Orig=('Coord Orig', 'first'),
            Coord_Dest=('Coord Dest', 'first')
        )
        .reset_index()
    )

    fluxo_animal['Distancia_km'] = fluxo_animal.apply(
        lambda row: distancia_haversine_km(row['Coord_Orig'], row['Coord_Dest']),
        axis=1
    )

    fluxo_animal = (
        fluxo_animal
        .sort_values('Total', ascending=False)
        .reset_index(drop=True)
    )

    fluxos_por_animal[animal] = fluxo_animal

fluxos_por_animal['Serpente'][
    ['Nome Orig', 'Nome Dest', 'Total', 'Distancia_km']
].head(20)

fluxos_por_animal['Serpente']['Total'].sum()

fluxo_geral = (
    com_fluxo_recentes
    .groupby(colunas_groupby, dropna=False, sort=False)
    .agg(
        Total=('Acidente', 'size'),
        Coord_Orig=('Coord Orig', 'first'),
        Coord_Dest=('Coord Dest', 'first')
    )
    .reset_index()
)

fluxo_geral['Distancia_km'] = fluxo_geral.apply(
    lambda row: distancia_haversine_km(row['Coord_Orig'], row['Coord_Dest']),
    axis=1
)

fluxo_geral = (
    fluxo_geral
    .sort_values('Total', ascending=False)
    .reset_index(drop=True)
)

fluxo_geral[['Nome Orig', 'Nome Dest', 'Total', 'Distancia_km']].head(20)

def weighted_quantile(values, weights, quantiles):
    values = np.array(values)
    weights = np.array(weights)
    quantiles = np.array(quantiles)

    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]

    cumulative_weights = np.cumsum(weights)
    cumulative_weights = cumulative_weights / cumulative_weights[-1]

    return np.interp(quantiles, cumulative_weights, values)

resumo_distancias_ponderado = []

for animal, df_fluxo in fluxos_por_animal.items():

    df_aux = df_fluxo.dropna(subset=['Distancia_km', 'Total']).copy()

    valores = df_aux['Distancia_km']
    pesos = df_aux['Total']

    q1, mediana, q3 = weighted_quantile(
        valores,
        pesos,
        [0.25, 0.50, 0.75]
    )

    media_ponderada = np.average(valores, weights=pesos)

    resumo_distancias_ponderado.append({
        'Acidente': animal,
        'Nº de ocorrências': pesos.sum(),
        'Nº de fluxos únicos': len(df_aux),
        'Média ponderada': media_ponderada,
        'Mínimo': valores.min(),
        'Q1': q1,
        'Mediana': mediana,
        'Q3': q3,
        'Máximo': valores.max()
    })

resumo_distancias_ponderado = pd.DataFrame(resumo_distancias_ponderado).round(2)

resumo_distancias_ponderado

resumo_distancias_ponderado = []

for animal, df_fluxo in fluxos_por_animal.items():

    df_aux = df_fluxo.dropna(subset=['Distancia_km', 'Total']).copy()

    valores = df_aux['Distancia_km']
    pesos = df_aux['Total']

    q1, mediana, q3 = weighted_quantile(
        valores,
        pesos,
        [0.25, 0.50, 0.75]
    )

    media_ponderada = np.average(valores, weights=pesos)

    resumo_distancias_ponderado.append({
        'Acidente': animal,
        'Nº de ocorrências': pesos.sum(),
        'Nº de fluxos únicos': len(df_aux),
        'Média ponderada': media_ponderada,
        'Mínimo': valores.min(),
        'Q1': q1,
        'Mediana': mediana,
        'Q3': q3,
        'Máximo': valores.max()
    })

resumo_distancias_ponderado = pd.DataFrame(resumo_distancias_ponderado).round(2)

resumo_distancias_ponderado

df_aux = fluxo_geral.dropna(subset=['Distancia_km', 'Total']).copy()

valores = df_aux['Distancia_km']
pesos = df_aux['Total']

q1, mediana, q3 = weighted_quantile(
    valores,
    pesos,
    [0.25, 0.50, 0.75]
)

media_ponderada = np.average(valores, weights=pesos)

resumo_fluxo_geral = pd.DataFrame([{
    'Acidente': 'Geral',
    'Nº de ocorrências': pesos.sum(),
    'Nº de fluxos únicos': len(df_aux),
    'Média ponderada': media_ponderada,
    'Mínimo': valores.min(),
    'Q1': q1,
    'Mediana': mediana,
    'Q3': q3,
    'Máximo': valores.max()
}]).round(2)

resumo_fluxo_geral

"""#### Grafo"""

import networkx as nx
import matplotlib.patches as mpatches

fluxo_geral.columns

# Criar um grafo direcionado
G = nx.DiGraph()

# Adicionar nós (cidades) e arestas
for _, row in fluxo_geral.iterrows():
    G.add_node(row["Nome Orig"], pos=(row["Coord_Orig"].x, row["Coord_Orig"].y),
               M=row["RRAS Orig"], RS=row["RS Orig"])
    G.add_node(row["Nome Dest"], pos=(row["Coord_Dest"].x, row["Coord_Dest"].y),
               M=row["RRAS Dest"], RS=row["RS Dest"])
    G.add_edge(row["Nome Orig"], row["Nome Dest"],
               weight=row["Total"], M=row["RRAS Dest"])

# Obter as posições dos nós
pos = nx.get_node_attributes(G, 'pos')

# Dicionário: dado código pega o nome da RRAS
dic_rras = gdf_munic[['Codigo Macrorregiao de Saude', 'Macrorregiao de Saude']].drop_duplicates().set_index('Codigo Macrorregiao de Saude')['Macrorregiao de Saude'].to_dict()

# Mapear cores diferentes para cada macrorregião nas arestas
macrorregioes = list(set(fluxo_geral["RRAS Dest"].dropna().unique()))
color_map = {m: plt.colormaps["tab10"](i % 10) for i, m in enumerate(macrorregioes)}
edge_colors = [color_map[G.edges[e]["M"]] if G.edges[e]["M"] in color_map else "gray" for e in G.edges]

# Ajustar a largura das arestas com base na frequência do trajeto
max_ocorrencias = max(fluxo_geral["Total"])
edge_widths = [(G.edges[e]["weight"] / max_ocorrencias) * 10 + 0.5 for e in G.edges]


# Determinar o município mais escolhido como destino por Regional de Saúde
cidade_mais_destino_por_RS = fluxo_geral.groupby("RS Dest")["Nome Dest"].agg(lambda x: x.value_counts().idxmax())

# Criar rótulos apenas para essas cidades
labels = {nome: nome for nome in cidade_mais_destino_por_RS.values}

# Plotar o grafo
plt.figure(figsize=(20, 12))
nx.draw_networkx_edges(G, pos, alpha=0.5, width=edge_widths, edge_color=edge_colors, arrows=False)
nx.draw_networkx_nodes(G, pos, node_color="gray", node_size=6, alpha=0.5)
nx.draw_networkx_labels(G, pos, labels, font_size=8, font_color="black")

# Criar legenda
legend_patches = [mpatches.Patch(color=color_map[m], label=dic_rras[m]) for m in macrorregioes if m in color_map]
plt.legend(handles=legend_patches, title="Macrorregiões", loc="upper right", fontsize=8)

# Exibir o gráfico no notebook
plt.show()

# -------------------------------
# MÉTRICAS DE CENTRALIDADE
# -------------------------------

# 1) In-degree centrality não ponderado
# Mede quantos municípios diferentes enviam pacientes para cada município
in_degree_centrality = nx.in_degree_centrality(G)

# 2) In-degree ponderado
# Mede o volume total de pacientes recebidos por município
pacientes_recebidos = dict(G.in_degree(weight='weight'))

# 3) Out-degree ponderado
# Mede o volume total de pacientes enviados por município
pacientes_enviados = dict(G.out_degree(weight='weight'))

metricas_rede = pd.DataFrame({
    'Municipio': list(G.nodes()),
    'In_degree_centrality': [in_degree_centrality.get(n, 0) for n in G.nodes()],
    'Pacientes_recebidos': [pacientes_recebidos.get(n, 0) for n in G.nodes()],
    'Pacientes_enviados': [pacientes_enviados.get(n, 0) for n in G.nodes()]
})

# Adiciona atributos dos nós, se quiser
metricas_rede['RRAS'] = metricas_rede['Municipio'].map(
    nx.get_node_attributes(G, 'M')
)

metricas_rede['RS'] = metricas_rede['Municipio'].map(
    nx.get_node_attributes(G, 'RS')
)

# Ordena pelos municípios que mais recebem pacientes
metricas_rede = metricas_rede.sort_values(
    'Pacientes_recebidos',
    ascending=False
)

metricas_rede.head(20)

"""##### Resultado apresentado"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
import networkx as nx

# =========================
# 1. Usar todos os fluxos
# =========================

fluxo_plot = fluxo_geral.copy()


# =========================
# 2. Função auxiliar para padronizar RRAS
# =========================

def rras_key(x):
    """
    Transforma valores como 1, '1', 'RRAS1' em inteiro 1.
    """
    if pd.isna(x):
        return np.nan
    return int(str(x).replace("RRAS", "").strip())


# =========================
# 3. Criar grafo com todos os fluxos
# =========================

G = nx.DiGraph()

for _, row in fluxo_plot.iterrows():
    G.add_node(
        row["Nome Orig"],
        pos=(row["Coord_Orig"].x, row["Coord_Orig"].y),
        M=rras_key(row["RRAS Orig"]),
        RS=row["RS Orig"]
    )

    G.add_node(
        row["Nome Dest"],
        pos=(row["Coord_Dest"].x, row["Coord_Dest"].y),
        M=rras_key(row["RRAS Dest"]),
        RS=row["RS Dest"]
    )

    G.add_edge(
        row["Nome Orig"],
        row["Nome Dest"],
        weight=row["Total"],
        M=rras_key(row["RRAS Dest"])
    )

pos = nx.get_node_attributes(G, "pos")


# =========================
# 4. Dicionário código RRAS -> nome RRAS
# =========================

gdf_plot = gdf_munic.copy()

gdf_plot["_RRAS_KEY"] = gdf_plot["Codigo Macrorregiao de Saude"].apply(rras_key)

dic_rras = (
    gdf_plot[
        ["_RRAS_KEY", "Macrorregiao de Saude"]
    ]
    .drop_duplicates()
    .set_index("_RRAS_KEY")["Macrorregiao de Saude"]
    .to_dict()
)


# =========================
# 5. Cores das RRAS para o fundo do mapa
# =========================
import re

def numero_rras(m):
    nome = str(dic_rras.get(m, f"RRAS{int(m)}"))
    return int(re.search(r"\d+", nome).group())

macrorregioes = sorted(
    gdf_plot["_RRAS_KEY"].dropna().unique(),
    key=numero_rras
)

cmap = plt.colormaps["tab20"]

color_map = {
    m: cmap(i % 20)
    for i, m in enumerate(macrorregioes)
}

gdf_plot["_cor_rras"] = gdf_plot["_RRAS_KEY"].map(color_map)


# =========================
# 6. Espessura das arestas
#    Fluxos maiores ficam mais espessos
# =========================

weights = np.array([G.edges[e]["weight"] for e in G.edges])

w_log = np.log1p(weights)

if w_log.max() > w_log.min():
    w_norm = (w_log - w_log.min()) / (w_log.max() - w_log.min())
else:
    w_norm = np.ones_like(w_log) * 0.5

# Espessura proporcional ao fluxo
edge_widths = 0.7 + 5.0 * w_norm

# Todas as arestas com mesma cor e mesma transparência
edge_color = "black"
edge_alpha = 0.3

# =========================
# 7. Cidades polo por Região de Saúde
# =========================

cidade_mais_destino_por_RS = (
    fluxo_geral
    .groupby("RS Dest")["Nome Dest"]
    .agg(lambda x: x.value_counts().idxmax())
)

polos = set(cidade_mais_destino_por_RS.values)

labels = {
    nome: nome
    for nome in G.nodes
    if nome in polos
}


# =========================
# 8. Plot
# =========================

fig, ax = plt.subplots(figsize=(28, 18))

# Fundo colorido por RRAS
gdf_plot.plot(
    ax=ax,
    color=gdf_plot["_cor_rras"],
    alpha=0.25,
    linewidth=0.25,
    edgecolor="white"
)

# Desenhar arestas uma a uma para permitir espessura variável
for i, e in enumerate(G.edges):
    nx.draw_networkx_edges(
        G,
        pos,
        edgelist=[e],
        ax=ax,
        width=edge_widths[i],
        edge_color=edge_color,
        alpha=edge_alpha,
        arrows=False,
        connectionstyle="arc3,rad=0.05"
    )

# Nós comuns
nos_comuns = [n for n in G.nodes if n not in polos]

nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=nos_comuns,
    ax=ax,
    node_size=10,
    node_color="gray",
    alpha=0.7
)

# Nós polos
nos_polos = [n for n in G.nodes if n in polos]

nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=nos_polos,
    ax=ax,
    node_size=95,
    node_color="black",
    alpha=1.0
)

# Rótulos dos polos
texts = nx.draw_networkx_labels(
    G,
    pos,
    labels=labels,
    ax=ax,
    font_size=13,
    font_color="black"
)

for text in texts.values():
    text.set_path_effects([
        pe.withStroke(linewidth=3, foreground="white")
    ])


# =========================
# 9. Legenda das RRAS
# =========================

legend_patches = [
    mpatches.Patch(
        color=color_map[m],
        label=dic_rras.get(m, f"RRAS{int(m)}")
    )
    for m in macrorregioes
]

leg = ax.legend(
    handles=legend_patches,
    title="Macrorregiões",
    # loc="lower left",
    # bbox_to_anchor=(0.01, 0.01),
    # bbox_to_anchor=(0.05, 0.1),
    loc="lower right",
    bbox_to_anchor=(0.95, 0.07),
    ncol=3,
    fontsize=15,
    title_fontsize=15,
    frameon=True,
    columnspacing=1.2,
    handletextpad=0.5,
    labelspacing=0.4,
    borderpad=0.8
)

leg.get_title().set_fontweight("bold")




# =========================
# 10. Título e ajustes finais
# =========================

fig.suptitle(
    "Fluxos intermunicipais de atendimento soroterápico, entre 2023 e 2025",
    fontsize=20,
    fontweight="bold",
    color="black",
    fontname="Arial",
    x=0.5,
    y=0.97,
    ha="center"
)

ax.set_axis_off()
ax.set_aspect("equal")

plt.tight_layout(rect=[0, 0, 1, 0.95])

plt.savefig(
    "grafo_fluxos.png",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
import networkx as nx
import re

# =========================
# 1. Usar todos os fluxos
# =========================

fluxo_plot = fluxo_geral.copy()


# =========================
# 2. Função auxiliar para padronizar RRAS
# =========================

def rras_key(x):
    """
    Transforma valores como 1, '1', 'RRAS1' em inteiro 1.
    """
    if pd.isna(x):
        return np.nan
    return int(str(x).replace("RRAS", "").strip())


# =========================
# 3. Criar grafo com todos os fluxos
# =========================

G = nx.DiGraph()

for _, row in fluxo_plot.iterrows():
    G.add_node(
        row["Nome Orig"],
        pos=(row["Coord_Orig"].x, row["Coord_Orig"].y),
        M=rras_key(row["RRAS Orig"]),
        RS=row["RS Orig"]
    )

    G.add_node(
        row["Nome Dest"],
        pos=(row["Coord_Dest"].x, row["Coord_Dest"].y),
        M=rras_key(row["RRAS Dest"]),
        RS=row["RS Dest"]
    )

    if G.has_edge(row["Nome Orig"], row["Nome Dest"]):
        G[row["Nome Orig"]][row["Nome Dest"]]["weight"] += row["Total"]
    else:
        G.add_edge(
            row["Nome Orig"],
            row["Nome Dest"],
            weight=row["Total"],
            M=rras_key(row["RRAS Dest"])
        )

pos = nx.get_node_attributes(G, "pos")


# # =========================
# # 4. Métricas da rede
# # =========================

# in_degree_centrality = nx.in_degree_centrality(G)
# pacientes_recebidos = dict(G.in_degree(weight="weight"))
# pacientes_enviados = dict(G.out_degree(weight="weight"))

# metricas_rede = pd.DataFrame({
#     'Municipio': list(G.nodes()),
#     'In_degree_centrality': [in_degree_centrality.get(n, 0) for n in G.nodes()],
#     'Pacientes_recebidos': [pacientes_recebidos.get(n, 0) for n in G.nodes()],
#     'Pacientes_enviados': [pacientes_enviados.get(n, 0) for n in G.nodes()]
# })

# metricas_rede['RRAS'] = metricas_rede['Municipio'].map(
#     nx.get_node_attributes(G, 'M')
# )

# metricas_rede['RS'] = metricas_rede['Municipio'].map(
#     nx.get_node_attributes(G, 'RS')
# )

# metricas_rede = metricas_rede.sort_values(
#     'Pacientes_recebidos',
#     ascending=False
# )


# =========================
# 5. Dicionário código RRAS -> nome RRAS
# =========================

gdf_plot = gdf_munic.copy()

gdf_plot["_RRAS_KEY"] = gdf_plot["Codigo Macrorregiao de Saude"].apply(rras_key)

dic_rras = (
    gdf_plot[["_RRAS_KEY", "Macrorregiao de Saude"]]
    .drop_duplicates()
    .set_index("_RRAS_KEY")["Macrorregiao de Saude"]
    .to_dict()
)


# =========================
# 6. Cores das RRAS para o fundo do mapa
# =========================

def numero_rras(m):
    nome = str(dic_rras.get(m, f"RRAS{int(m)}"))
    return int(re.search(r"\d+", nome).group())

macrorregioes = sorted(
    gdf_plot["_RRAS_KEY"].dropna().unique(),
    key=numero_rras
)

cmap = plt.colormaps["tab20"]

color_map = {
    m: cmap(i % 20)
    for i, m in enumerate(macrorregioes)
}

gdf_plot["_cor_rras"] = gdf_plot["_RRAS_KEY"].map(color_map)


# =========================
# 7. Espessura das arestas
# =========================

weights = np.array([G.edges[e]["weight"] for e in G.edges])

w_log = np.log1p(weights)

if w_log.max() > w_log.min():
    w_norm = (w_log - w_log.min()) / (w_log.max() - w_log.min())
else:
    w_norm = np.ones_like(w_log) * 0.5

edge_widths = 0.7 + 5.0 * w_norm
edge_color = "black"
edge_alpha = 0.3


# =========================
# 8. Cidades polo por Região de Saúde
# =========================

cidade_mais_destino_por_RS = (
    fluxo_geral
    .groupby("RS Dest")["Nome Dest"]
    .agg(lambda x: x.value_counts().idxmax())
)

polos = set(cidade_mais_destino_por_RS.values)

labels = {
    nome: nome
    for nome in G.nodes
    if nome in polos
}


# =========================
# 9. Preparar tabela top 20
# =========================

top20 = metricas_rede[['Municipio', 'Pacientes_recebidos']].head(20).copy()
top20['Pacientes_recebidos'] = top20['Pacientes_recebidos'].astype(int)

# Se quiser encurtar nomes muito longos, descomente:
# top20['Municipio'] = top20['Municipio'].apply(
#     lambda x: x if len(str(x)) <= 24 else str(x)[:24] + '...'
# )


# =========================
# 10. Plot principal
# =========================

fig, ax = plt.subplots(figsize=(28, 18))

# Fundo colorido por RRAS
gdf_plot.plot(
    ax=ax,
    color=gdf_plot["_cor_rras"],
    alpha=0.25,
    linewidth=0.25,
    edgecolor="white"
)

# Desenhar arestas uma a uma
for i, e in enumerate(G.edges):
    nx.draw_networkx_edges(
        G,
        pos,
        edgelist=[e],
        ax=ax,
        width=edge_widths[i],
        edge_color=edge_color,
        alpha=edge_alpha,
        arrows=False,
        connectionstyle="arc3,rad=0.05"
    )

# Nós comuns
nos_comuns = [n for n in G.nodes if n not in polos]

nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=nos_comuns,
    ax=ax,
    node_size=10,
    node_color="gray",
    alpha=0.7
)

# Nós polos
nos_polos = [n for n in G.nodes if n in polos]

nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=nos_polos,
    ax=ax,
    node_size=95,
    node_color="black",
    alpha=1.0
)

# Rótulos dos polos
texts = nx.draw_networkx_labels(
    G,
    pos,
    labels=labels,
    ax=ax,
    font_size=13,
    font_color="black"
)

for text in texts.values():
    text.set_path_effects([
        pe.withStroke(linewidth=3, foreground="white")
    ])


# =========================
# 11. Legenda das RRAS
# =========================

legend_patches = [
    mpatches.Patch(
        color=color_map[m],
        label=dic_rras.get(m, f"RRAS{int(m)}")
    )
    for m in macrorregioes
]

leg = ax.legend(
    handles=legend_patches,
    title="Macrorregiões",
    loc="lower right",
    bbox_to_anchor=(0.95, 0.07),
    ncol=3,
    fontsize=13,
    title_fontsize=14,
    frameon=True,
    columnspacing=1.2,
    handletextpad=0.5,
    labelspacing=0.4,
    borderpad=0.8
)

leg.get_title().set_fontweight("bold")


# =========================
# 12. Tabela no canto inferior esquerdo
# =========================

# [left, bottom, width, height]
ax_tabela = fig.add_axes([0.055, 0.08, 0.25, 0.36])
ax_tabela.axis('off')
ax_tabela.set_facecolor((1, 1, 1, 0.96))

tabela = ax_tabela.table(
    cellText=top20.values,
    colLabels=["Município", "Pacientes"],
    cellLoc='center',
    colLoc='center',
    loc='center',
    colWidths=[0.72, 0.28]
)

tabela.auto_set_font_size(False)
tabela.set_fontsize(10)
tabela.scale(1.08, 1.32)

# Estilo da tabela
for (row, col), cell in tabela.get_celld().items():
    cell.set_edgecolor("#9E9E9E")
    cell.set_linewidth(0.6)

    if row == 0:
        cell.set_facecolor("#D9D9D9")
        cell.set_text_props(weight='bold', color='black', fontsize=10.5)
    else:
        # linhas alternadas
        if row % 2 == 0:
            cell.set_facecolor((0.96, 0.96, 0.96, 0.96))
        else:
            cell.set_facecolor((1, 1, 1, 0.96))

# Alinhar texto por coluna
for i in range(1, len(top20) + 1):
    tabela[(i, 0)].get_text().set_ha('left')   # Município
    tabela[(i, 1)].get_text().set_ha('right')  # Pacientes

# Título da tabela
ax_tabela.set_title(
    "Principais municípios receptores\nde pacientes",
    fontsize=12,
    fontweight="bold",
    pad=10
)


# =========================
# 13. Título e ajustes finais
# =========================

fig.suptitle(
    "Fluxos intermunicipais de atendimento soroterápico, entre 2023 e 2025",
    fontsize=20,
    fontweight="bold",
    x=0.5,
    y=0.97,
    ha="center"
)

ax.set_axis_off()
ax.set_aspect("equal")

plt.tight_layout(rect=[0, 0, 1, 0.95])

plt.savefig(
    "grafo_fluxos_com_tabela.png",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
import networkx as nx
import re

plt.rcParams["font.family"] = "DejaVu Sans"

# =========================
# 1. Usar todos os fluxos
# =========================

fluxo_plot = fluxo_geral.copy()


# =========================
# 2. Função auxiliar para padronizar RRAS
# =========================

def rras_key(x):
    """
    Transforma valores como 1, '1', 'RRAS1' em inteiro 1.
    """
    if pd.isna(x):
        return np.nan
    return int(str(x).replace("RRAS", "").strip())


# =========================
# 3. Criar grafo com todos os fluxos
# =========================

G = nx.DiGraph()

for _, row in fluxo_plot.iterrows():

    G.add_node(
        row["Nome Orig"],
        pos=(row["Coord_Orig"].x, row["Coord_Orig"].y),
        M=rras_key(row["RRAS Orig"]),
        RS=row["RS Orig"]
    )

    G.add_node(
        row["Nome Dest"],
        pos=(row["Coord_Dest"].x, row["Coord_Dest"].y),
        M=rras_key(row["RRAS Dest"]),
        RS=row["RS Dest"]
    )

    origem = row["Nome Orig"]
    destino = row["Nome Dest"]
    peso = row["Total"]

    if G.has_edge(origem, destino):
        G[origem][destino]["weight"] += peso
    else:
        G.add_edge(
            origem,
            destino,
            weight=peso,
            M=rras_key(row["RRAS Dest"])
        )

pos = nx.get_node_attributes(G, "pos")


# =========================
# 4. Métricas da rede
# =========================

in_degree_centrality = nx.in_degree_centrality(G)
pacientes_recebidos = dict(G.in_degree(weight="weight"))
pacientes_enviados = dict(G.out_degree(weight="weight"))

metricas_rede = pd.DataFrame({
    "Municipio": list(G.nodes()),
    "In_degree_centrality": [in_degree_centrality.get(n, 0) for n in G.nodes()],
    "Pacientes_recebidos": [pacientes_recebidos.get(n, 0) for n in G.nodes()],
    "Pacientes_enviados": [pacientes_enviados.get(n, 0) for n in G.nodes()]
})

metricas_rede["RRAS"] = metricas_rede["Municipio"].map(
    nx.get_node_attributes(G, "M")
)

metricas_rede["RS"] = metricas_rede["Municipio"].map(
    nx.get_node_attributes(G, "RS")
)

metricas_rede = metricas_rede.sort_values(
    "Pacientes_recebidos",
    ascending=False
)


# =========================
# 5. Preparar tabela top 20
# =========================

top20 = (
    metricas_rede[["Municipio", "Pacientes_recebidos"]]
    .head(10)
    .copy()
    .reset_index(drop=True)
)

top20["Pacientes_recebidos"] = top20["Pacientes_recebidos"].astype(int)

top20 = top20.rename(columns={
    "Municipio": "Município",
    "Pacientes_recebidos": "Pacientes"
})


# =========================
# 6. Dicionário código RRAS -> nome RRAS
# =========================

gdf_plot = gdf_munic.copy()

gdf_plot["_RRAS_KEY"] = gdf_plot["Codigo Macrorregiao de Saude"].apply(rras_key)

dic_rras = (
    gdf_plot[["_RRAS_KEY", "Macrorregiao de Saude"]]
    .drop_duplicates()
    .set_index("_RRAS_KEY")["Macrorregiao de Saude"]
    .to_dict()
)


# =========================
# 7. Cores das RRAS para o fundo do mapa
# =========================

def numero_rras(m):
    nome = str(dic_rras.get(m, f"RRAS{int(m)}"))
    achou = re.search(r"\d+", nome)
    if achou:
        return int(achou.group())
    return int(m)

macrorregioes = sorted(
    gdf_plot["_RRAS_KEY"].dropna().unique(),
    key=numero_rras
)

cmap = plt.colormaps["tab20"]

color_map = {
    m: cmap(i % 20)
    for i, m in enumerate(macrorregioes)
}

gdf_plot["_cor_rras"] = gdf_plot["_RRAS_KEY"].map(color_map)


# =========================
# 8. Espessura das arestas
# =========================

edge_list = list(G.edges())

weights = np.array([
    G.edges[e]["weight"]
    for e in edge_list
])

w_log = np.log1p(weights)

if w_log.max() > w_log.min():
    w_norm = (w_log - w_log.min()) / (w_log.max() - w_log.min())
else:
    w_norm = np.ones_like(w_log) * 0.5

edge_widths = 0.7 + 5.0 * w_norm

edge_color = "black"
edge_alpha = 0.3


# =========================
# 9. Cidades polo por Região de Saúde
# =========================

cidade_mais_destino_por_RS = (
    fluxo_geral
    .groupby("RS Dest")["Nome Dest"]
    .agg(lambda x: x.value_counts().idxmax())
)

polos = set(cidade_mais_destino_por_RS.values)

labels = {
    nome: nome
    for nome in G.nodes
    if nome in polos
}


# =========================
# 10. Plot principal
# =========================

fig, ax = plt.subplots(figsize=(28, 18))

# Fundo colorido por RRAS
gdf_plot.plot(
    ax=ax,
    color=gdf_plot["_cor_rras"],
    alpha=0.25,
    linewidth=0.25,
    edgecolor="white"
)

# Arestas
for i, e in enumerate(edge_list):
    nx.draw_networkx_edges(
        G,
        pos,
        edgelist=[e],
        ax=ax,
        width=edge_widths[i],
        edge_color=edge_color,
        alpha=edge_alpha,
        arrows=False,
        connectionstyle="arc3,rad=0.05"
    )

# Nós comuns
nos_comuns = [n for n in G.nodes if n not in polos]

nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=nos_comuns,
    ax=ax,
    node_size=10,
    node_color="gray",
    alpha=0.7
)

# Nós polos
nos_polos = [n for n in G.nodes if n in polos]

nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=nos_polos,
    ax=ax,
    node_size=95,
    node_color="black",
    alpha=1.0
)

# Rótulos dos polos
texts = nx.draw_networkx_labels(
    G,
    pos,
    labels=labels,
    ax=ax,
    font_size=15,
    font_color="black"
)

for text in texts.values():
    text.set_path_effects([
        pe.withStroke(linewidth=3, foreground="white")
    ])


# =========================
# 11. Legenda das RRAS
# =========================

legend_patches = [
    mpatches.Patch(
        color=color_map[m],
        label=dic_rras.get(m, f"RRAS{int(m)}")
    )
    for m in macrorregioes
]

leg = ax.legend(
    handles=legend_patches,
    title="Macrorregiões",
    loc="lower right",
    bbox_to_anchor=(0.95, 0.07),
    ncol=3,
    # fontsize=13,
    # title_fontsize=14,
    fontsize=14,
    title_fontsize=16,
    frameon=True,
    columnspacing=1.2,
    handletextpad=0.5,
    labelspacing=0.4,
    borderpad=0.8
)

leg.get_title().set_fontweight("bold")


# =========================
# 12. Painel com principais municípios receptores
# =========================

# [left, bottom, width, height]
# bottom menor e height menor para a tabela ficar mais embaixo
ax_tabela = fig.add_axes([0.035, 0.025, 0.30, 0.30], zorder=20)

ax_tabela.set_xlim(0, 1)
ax_tabela.set_ylim(0, 1)
ax_tabela.axis("off")

# Fundo arredondado
fundo = mpatches.FancyBboxPatch(
    (0, 0),
    1,
    1,
    boxstyle="round,pad=0.018,rounding_size=0.018",
    linewidth=0.9,
    edgecolor=(0.45, 0.45, 0.45, 0.55),
    facecolor=(1, 1, 1, 0.90),
    transform=ax_tabela.transAxes,
    zorder=0
)

ax_tabela.add_patch(fundo)

# Título do painel
ax_tabela.text(
    # 0.5,
    # 0.92,
    0.48,
    0.92,
    "Principais municípios receptores de pacientes",
    ha="center",
    # va="top",
    va="center",
    # fontsize=12.5,
    fontsize=18,
    fontweight="bold",
    color="black"
)

# Cabeçalho
ax_tabela.text(
    0.07,
    0.76,
    "Município",
    ha="left",
    va="center",
    # fontsize=10.8,
    fontsize=18,
    fontweight="bold",
    color="black"
)

ax_tabela.text(
    0.88,
    0.76,
    "Pacientes",
    ha="right",
    va="center",
    # fontsize=10.8,
    fontsize=18,
    fontweight="bold",
    color="black"
)

# Linha do cabeçalho
ax_tabela.plot(
    [0.055, 0.90],
    [0.72, 0.72],
    color=(0.35, 0.35, 0.35, 0.55),
    linewidth=0.9
)

# Linhas do painel
y_inicio = 0.66
espacamento = 0.055

for i, row in top20.iterrows():

    y = y_inicio - i * espacamento

    # Faixa alternada
    if i % 2 == 0:
        faixa = mpatches.Rectangle(
            (0.045, y - 0.024),
            0.86,
            0.045,
            transform=ax_tabela.transAxes,
            facecolor=(0.90, 0.90, 0.90, 0.42),
            edgecolor="none",
            zorder=0.5
        )
        ax_tabela.add_patch(faixa)

    # Nome do município
    ax_tabela.text(
        0.07,
        y,
        str(row["Município"]),
        ha="left",
        va="center",
        # fontsize=9.8,
        fontsize=19,
        color="black"
    )

    # Número de pacientes
    ax_tabela.text(
        0.88,
        y,
        f'{row["Pacientes"]:,}'.replace(",", "."),
        ha="right",
        va="center",
        # fontsize=9.8,
        fontsize=19,
        color="black"
    )
# =========================
# 13. Título e ajustes finais
# =========================

fig.suptitle(
    "Fluxos intermunicipais de atendimento soroterápico, entre 2023 e 2025",
    fontsize=20,
    fontweight="bold",
    color="black",
    x=0.5,
    y=0.97,
    ha="center"
)

ax.set_axis_off()
ax.set_aspect("equal")

plt.subplots_adjust(left=0.02, right=0.98, bottom=0.02, top=0.94)

plt.savefig(
    "grafo_fluxos_com_tabela.png",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

"""##### Grafo em preto e branco
**Trocando a legenda: Código da RRAS $\rightarrow$ Nome da RRAS**
"""

# Criar um grafo direcionado
Gc = nx.DiGraph()

# Adicionar nós (cidades) e arestas
for _, row in fluxo_geral.iterrows():
    Gc.add_node(row["Nome Orig"], pos=(row["Coord_Orig"].x, row["Coord_Orig"].y),
               M=row["RRAS Orig"], RS=row["RS Orig"])
    Gc.add_node(row["Nome Dest"], pos=(row["Coord_Dest"].x, row["Coord_Dest"].y),
               M=row["RRAS Dest"], RS=row["RS Dest"])
    Gc.add_edge(row["Nome Orig"], row["Nome Dest"],
               weight=row["Total"], M=row["RRAS Dest"])

# Obter as posições dos nós
pos_c = nx.get_node_attributes(Gc, 'pos')

# Dicionário: dado código pega o nome da RRAS
dic_rras = gdf_munic[['Codigo Macrorregiao de Saude', 'Macrorregiao de Saude']].drop_duplicates().set_index('Codigo Macrorregiao de Saude')['Macrorregiao de Saude'].to_dict()

# Mapear cores diferentes para cada macrorregião nas arestas
macrorregioes_c = list(set(fluxo_geral["RRAS Dest"].dropna().unique()))
# Generate a range of grayscale values from 0 to 1, one for each macrorregiao
grayscale_values = np.linspace(0.05, 0.9, len(macrorregioes_c)) # Avoid pure black/white for better visibility
color_map_c = {m: plt.colormaps["Greys_r"](grayscale_values[i]) for i, m in enumerate(macrorregioes_c)}
#color_map_c = {m: 'lightgrey' for i, m in enumerate(macrorregioes_c)}
edge_colors_c = [color_map_c[Gc.edges[e]["M"]] if Gc.edges[e]["M"] in color_map_c else "gray" for e in Gc.edges]

# Ajustar a largura das arestas com base na frequência do trajeto
max_ocorrencias_c = max(fluxo_geral["Total"])
edge_widths_c = [(Gc.edges[e]["weight"] / max_ocorrencias) * 10 + 0.5 for e in Gc.edges]


# Determinar o município mais escolhido como destino por Regional de Saúde
cidade_mais_destino_por_RS_c = fluxo_geral.groupby("RS Dest")["Nome Dest"].agg(lambda x: x.value_counts().idxmax())

# Criar rótulos apenas para essas cidades
labels_c = {nome: nome for nome in cidade_mais_destino_por_RS_c.values}

import matplotlib.patheffects as pe

# Plotar o grafo
plt.figure(figsize=(20, 12))
nx.draw_networkx_edges(Gc, pos_c, alpha=1, width=edge_widths_c, edge_color=edge_colors_c, arrows=False)
nx.draw_networkx_nodes(Gc, pos_c, node_color="gray", node_size=6, alpha=0)
texts = nx.draw_networkx_labels(Gc, pos_c, labels_c, font_size=7, font_color="black")

# adiciona borda branca
for text in texts.values():
    text.set_path_effects([
        pe.withStroke(linewidth=2, foreground="white")
    ])

# Criar legenda
legend_patches = [mpatches.Patch(color=color_map_c[m], label=dic_rras[m]) for m in macrorregioes_c if m in color_map_c]
plt.legend(handles=legend_patches, title="Macrorregiões", loc="upper right", fontsize=8)

# Exibir o gráfico no notebook
plt.show()

"""#### Boxplots"""

dfs_box = []

for animal, df_fluxo in fluxos_por_animal.items():
    df_aux = df_fluxo[['Distancia_km']].dropna().copy()
    df_aux['Acidente'] = animal
    dfs_box.append(df_aux)

box_dist = pd.concat(dfs_box, ignore_index=True)

ordem_animais = ['Escorpião', 'Aranha', 'Serpente', 'Abelha', 'Outros', 'Lagarta', 'Não informado']

box_dist['Acidente'] = pd.Categorical(
    box_dist['Acidente'],
    categories=ordem_animais,
    ordered=True
)

box_dist = box_dist.sort_values('Acidente')

fig = px.box(
    box_dist,
    x='Acidente',
    y='Distancia_km',
    points='outliers',  # pode usar 'all' se quiser mostrar todos
    title='Distribuição das distâncias dos fluxos intermunicipais por tipo de acidente',
    labels={
        'Acidente': 'Tipo de acidente',
        'Distancia_km': 'Distância entre origem e destino (km)'
    },
    color='Acidente',
    color_discrete_sequence=px.colors.qualitative.Safe
)

fig.update_layout(
    showlegend=False,
    annotations=[
        dict(
            text='Fonte: SINAN – DATASUS',
            xref='paper', yref='paper',
            x=0, y=-0.18,
            showarrow=False,
            font=dict(size=12, color='gray'),
            align='left'
        )
    ],
    margin=dict(b=100)
)

fig.show()

dfs_box_pond = []

for animal, df_fluxo in fluxos_por_animal.items():
    df_aux = df_fluxo[['Distancia_km', 'Total']].dropna().copy()
    df_aux['Acidente'] = animal

    df_rep = df_aux.loc[df_aux.index.repeat(df_aux['Total'])].copy()
    df_rep = df_rep[['Acidente', 'Distancia_km']]

    dfs_box_pond.append(df_rep)

box_dist_pond = pd.concat(dfs_box_pond, ignore_index=True)

box_dist_pond['Acidente'] = pd.Categorical(
    box_dist_pond['Acidente'],
    categories=ordem_animais,
    ordered=True
)

box_dist_pond = box_dist_pond.sort_values('Acidente')

fig = px.box(
    box_dist_pond,
    x='Acidente',
    y='Distancia_km',
    points='outliers',
    title='Distribuição ponderada das distâncias dos fluxos intermunicipais por tipo de acidente',
    labels={
        'Acidente': 'Tipo de acidente',
        'Distancia_km': 'Distância entre origem e destino (km)'
    },
    color='Acidente',
    color_discrete_sequence=px.colors.qualitative.Safe
)

fig.update_layout(
    showlegend=False,
    annotations=[
        dict(
            text='Fonte: SINAN – DATASUS',
            xref='paper', yref='paper',
            x=0, y=-0.18,
            showarrow=False,
            font=dict(size=12, color='gray'),
            align='left'
        )
    ],
    margin=dict(b=100)
)

fig.show()

fig = px.box(
    box_dist_pond,
    x='Acidente',
    y='Distancia_km',
    points='outliers',
    title='Distribuição das distâncias dos fluxos intermunicipais por tipo de acidente',
    labels={
        'Acidente': 'Tipo de acidente',
        'Distancia_km': 'Distância entre origem e destino (km)'
    },
    color='Acidente',
    color_discrete_sequence=px.colors.qualitative.Safe
)

fig.update_yaxes(range=[0, 80])

fig.update_layout(
    showlegend=False,
    annotations=[
        dict(
            text='Fonte: SINAN – DATASUS',
            xref='paper', yref='paper',
            x=0, y=-0.18,
            showarrow=False,
            font=dict(size=12, color='gray'),
            align='left'
        )
    ],
    margin=dict(b=100)
)

fig.show()

